"""define-book-table

Revision ID: 770c0fd7afaf
Revises: dcf6d9d6538a
Create Date: 2021-12-24 16:38:22.172569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770c0fd7afaf'
down_revision = 'dcf6d9d6538a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.Enum('available', 'unavailable', name='bookstatus'), nullable=False),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('profile_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['book_profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
